[package]
name = "conv_nn_mnist"
version = "0.1.0"
authors = ["suztomo <suztomo+github@gmail.com>"]

[dependencies]
ansi_term = "0.11"
assert_approx_eq = "1.0.0"
csv = "1.0"
lazy_static = "1.1.0"
mindtree_utils = "0.4.0"
ndarray = "0.12.1"
ndarray-rand = "0.8.0"
rand = "0.5.5"
num-traits = "0.2"
