(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               (set! hoge 100)
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set ! balance (+ balance (amount)))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- Make-account" m))))
  dispatch)

